# /etc/pkgrs/use_mappings.conf
# Формат: Флаг_Gentoo = фича_Cargo

# Графика, Интерфейс и Дисплейные сервера
wayland = wayland
xwayland = xwayland
vulkan = vulkan
opengl = opengl
gles2 = gles2
egl = egl
#gtk = gtk
#gtk3 = gtk3
#gtk4 = gtk4
gtk+ = gtk
cairo = cairo
pango = pango
harfbuzz = harfbuzz
fontconfig = fontconfig
corefonts = font
qt6 = qt6
qml = qml
introspection = introspection
debug
# Звук и Видео (Кодеки и Серверы)
alsa = alsa
ffmpeg = ffmpeg
gstreamer = gstreamer
v4l = v4l2
aac = aac
flac = flac
mp3 = mp3
mp4 = mp4
mpeg = mpeg
mpg123 = mpg123
h264 = h264
x264 = x264
x265 = x265
openh264 = openh264
opus = opus
wavpack = wavpack
png = png
jpeg = jpeg
jpeg2k = jpeg2k

# Системные вызовы, Безопасность и Архитектура
pam = pam
su = su
dbus = dbus
elogind = elogind
udisks = udisks
usb = usb
kmod = kmod
libzfs = zfs
bluetooth = bluetooth
networkmanager = networkmanager
ssh = ssh
initramfs = initramfs
dracut = dracut
dist-kernel = kernel
dev-rust = rust
rust = rust

# Сжатие и Оптимизации компилятора
zstd = zstd
lz4 = lz4
zip = zip
asm = asm
jit = jit
llvm = llvm

# Дополнительные системные библиотеки
xml = xml
icu = icu
idn = idn
lua_single_target_lua5-4 = lua
luajit = luajit
# Форматы конфигурации для приложений
toml = toml
json = json
yaml = yaml
http = http
debug = debug
